In [39]:
import os
import re
from datetime import timedelta
import numpy as np
import pandas as pd

In [19]:
file_list = os.listdir('data')
file_list

['2021-10-11-19-59-20.xlsx']

In [60]:
df

for file in file_list:
    df = pd.read_excel('data/' + file)


df.head()

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
0,0,K26_sDKnvMU,Toy Story (1995) Trailer 2 (VHS Capture),Trailer for Toy Story (1995) captured from the...,99.0,12.0,0.0,13.0,At first Toy Story wasn't confirmed as a Pixat...,PT1M31S,102865.0
1,1,3LPANjHlPxo,Jumanji Trailer 1995,Jumanji Trailer 1995\nDirector: Joe Johnston\n...,249.0,29.0,0.0,NaN,NaN,PT2M48S,175902.0
2,2,rEnOoWs3FuA,Grumpier Old Men - Trailer,"The more things change, the more they stay the...",218.0,8.0,0.0,12.0,1:36 *GRUMPY⬅️ER* \n *GRUMPIER* . I'm ...,PT1M51S,164912.0
3,3,j9xml1CxgXI,Waiting To Exhale,Whitney Houston and Angela Bassett star in thi...,NaN,NaN,0.0,NaN,NaN,PT2M39S,367976.0
4,4,ltwvKLnj1B4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df.isnull().sum()

index              0
youtubeId          0
title              0
description      101
likeCount        464
dislikeCount     464
favoriteCount      0
commentCount     399
comments_100     639
duration           0
viewCount         26
dtype: int64

In [62]:
df.dropna(subset=['title'], inplace=True)

In [63]:
df[df['description'].isnull()]

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
97,97,oA7M9qSJKrE,Heidi Fleiss: Hollywood Madam,NaN,42.0,2.0,0.0,NaN,NaN,PT1M8S,27283.0
127,127,_d7KNUnJF4o,Pie In The Sky Trailer,NaN,3.0,3.0,0.0,2.0,This is the wrong trailer... not the Brigid Be...,PT1M21S,11863.0
156,156,BBEB9OSfeCA,Casper (1995) - U.K. Theatrical Trailer,NaN,957.0,49.0,0.0,93.0,We never got a third Addams Family movie with ...,PT1M56S,463673.0
171,171,43-BefmjMFg,Judge Dredd (trailer),NaN,790.0,59.0,0.0,346.0,I loved the trailers back in those days! . 201...,PT2M9S,576348.0
234,234,G8ZHyJoKYnM,"Forget Paris, 1995 trailer",NaN,226.0,11.0,0.0,20.0,I wish I was binge watching these types of rom...,PT1M53S,110651.0
...,...,...,...,...,...,...,...,...,...,...,...
5218,5218,Dzt5dMoS5dA,The Horse's Mouth (1958) - original trailer,NaN,35.0,0.0,0.0,2.0,"Guinness fan. Never seen, or even, heard of it...",PT1M45S,9614.0
5242,5242,oVZMHp-BaRs,The Powerpuff Girls Movie 2002,NaN,2.0,1.0,0.0,0.0,NaN,PT59S,850.0
5252,5252,QNi9o5HUcuU,The Importance of Being Earnest (1952) trailer,NaN,NaN,NaN,0.0,NaN,NaN,PT2M46S,11272.0
5269,5269,-ZDvhYsm2as,Harry And Walter Go To New York,NaN,28.0,2.0,0.0,4.0,Been my favorite movie comedy since I saw it i...,PT2M18S,11751.0
5287,5287,vMg7LZ-JF6I,Blood Work - Theatrical Trailer,NaN,307.0,15.0,0.0,35.0,Does anyone know who does the narration for th...,PT1M40S,124635.0

In [67]:
def convert_string_to_seconds(duration):
    hours_pattern = re.compile(r'(\d+)H')
    minutes_pattern = re.compile(r'(\d+)M')
    seconds_pattern = re.compile(r'(\d+)S')

    hours = hours_pattern.search(duration)
    minutes = minutes_pattern.search(duration)
    seconds = seconds_pattern.search(duration)


    hours = int(hours.group(1)) if hours else 0
    minutes = int(minutes.group(1)) if minutes else 0
    seconds = int(seconds.group(1)) if seconds else 0

    video_seconds = timedelta(
        hours = hours,
        minutes = minutes,
        seconds = seconds
    ).total_seconds()

    return video_seconds

In [66]:
df['duration'] = df['duration'].apply(convert_string_to_seconds)

P0D

## Top 10 videos

In [68]:
df.sort_values(by='viewCount', ascending=False)[:10]

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
5147,5147,j-V12tL78Mc,Unfaithful (2002) - The Other Woman Scene (1/3...,Unfaithful movie clips: http://j.mp/1ixkUnl\nB...,65970.0,32628.0,0.0,4954.0,she dersved . Me encanta esta película!!! . Pa...,163.0,122417208.0
1762,1762,gv2AOQiGAwg,HIGH ART - trailer PL,"zwiastun filmu „High Art""_x000D_\nReż. Lisa Ch...",6902.0,4774.0,0.0,200.0,صاقطين . .€π=¥£€¥•¥¥√√ . lol . 0.50 💞mmmmm cyc...,88.0,19685025.0
3486,3486,4FHpmn-KYec,A time for us Romeo and Juliet 1968,NaN,75806.0,2196.0,0.0,4134.0,I AM from México city october 2021\nI AM liste...,260.0,14829709.0
5240,5240,HTHJyw1UsLM,Like Mike (2002) Official Trailer # 1 -Bow Wow HD,Check out the official The Painted Veil (2006)...,54459.0,3475.0,0.0,0.0,NaN,171.0,12817188.0
1616,1616,2e-eXJ6HgkQ,Titanic - Official Trailer (HD),Leonardo DiCaprio and Oscar-nominatee Kate Win...,NaN,NaN,0.0,NaN,NaN,116.0,12257294.0
2828,2828,NJIjNs_s2NI,RoboCop 2 (3/11) Movie CLIP - Robo Flops (1990...,RoboCop 2 movie clips: http://j.mp/1AUQliM\nBU...,86393.0,2995.0,0.0,6697.0,Wow I've just subscribed BUT do I read correct...,133.0,11402173.0
1963,1963,BBgghnQF6E4,Walt Disney Animation Studios' Steamboat Willie,The classic Mickey Mouse cartoon,94524.0,3229.0,0.0,NaN,NaN,443.0,10674758.0
3762,3762,lgo3Hb5vWLE,Requiem for a Dream Trailer,Requiem for a Dream exposes four paralleled in...,11236.0,687.0,0.0,4200.0,Alfred Hitchcock would be proud. . 2014- now\n...,94.0,8119474.0
1712,1712,FpfDTg4lbNE,Carne Trémula (Live Flesh) - Official Trailer,we have a new channel for horror/sci-fi fans: ...,1232.0,948.0,0.0,67.0,"Me: ""huh, this seems like a normal family movi...",95.0,7424799.0
545,545,vHLgob-PpIk,HD 1080p | Tim Burton's The Nightmare Before C...,"This is the introduction to Tim Burton's ""The ...",31186.0,2390.0,0.0,2748.0,QWEFGHJNMMMMMMMMMMWERTHHJJKNNMMMMMMMMMMMMMMMMM...,269.0,6761885.0

## Bottom 10 videos

In [69]:
sorted_df = df.sort_values(by='viewCount', ascending=True)

sorted_df[sorted_df['viewCount']>0][:10]

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
1719,1719,ZGjNEbDJk6M,The Big Band Convention - Live 02.07.1998 - Lo...,"Mit ""The Big Band Convention"" hat sich in der ...",0.0,0.0,0.0,0.0,NaN,210.0,225.0
1688,1688,dzYCTejXbx0,Eden Let Your Spirits Soar Trailer 1998,Eden Let Your Spirits Soar Trailer 1998\nDirec...,1.0,0.0,0.0,0.0,NaN,112.0,258.0
2823,2823,DaezhUFweTY,"""Brother, Can You Spare a Dime?"": The Great De...",Mr. Faulk Landrum talks to the Read Through th...,2.0,0.0,0.0,0.0,NaN,4129.0,343.0
3346,3346,_3o4gqFnAP4,"Best Of ""Sacco E Vanzetti"" (1971)",http://www.imdb.com/title/tt0067698/\n\nLegend...,1.0,0.0,0.0,0.0,NaN,71.0,399.0
1057,1057,1AfBwPrB4pM,The Leopard Son Trailer 1996,The Leopard Son Trailer 1996\nDirector: Hugo V...,0.0,0.0,0.0,0.0,NaN,64.0,503.0
3022,3022,WtxXTxKmNxs,Trans (1998) Movie Review,Trans was written and directed by Julian Goldb...,6.0,2.0,0.0,7.0,This is the only thing I can find on this movi...,182.0,577.0
2670,2670,Fn02k1dx1Ns,Rosie (1998) Movie Review,Rosie was directed by Patrice Toye. This movie...,5.0,0.0,0.0,2.0,"Yes, have looked for this scarce movie myself...",188.0,660.0
3407,3407,JYREWGLGEnI,The King of Marvin Gardens - Trailer,"A Philadelphia radio personality, David (Jack ...",NaN,NaN,0.0,NaN,NaN,81.0,717.0
708,708,7AG6yN9JP5g,SPITFIRE - RUBBER ROSIE (LOWLIFE RECORDINGS 1994),SPITFIRE - RUBBER ROSIE - LOWLIFE RECORDINGS 1...,13.0,0.0,0.0,1.0,Basement club - 90s - rock n roll baby,199.0,763.0
856,856,xWGteh1hSlk,The Philadelphia Story 1940 Trailer,Philadelphia heiress Tracy Lord throws out her...,1.0,0.0,0.0,0.0,NaN,212.0,813.0

## Most liked video

In [35]:
df.sort_values(by='likeCount', ascending=False)[:1]

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
1963,1963,BBgghnQF6E4,Walt Disney Animation Studios' Steamboat Willie,The classic Mickey Mouse cartoon,94524.0,3229.0,0.0,NaN,NaN,PT7M23S,10674758.0

## Least liked video

In [58]:
df[df['youtubeId']=='ybhS3G0ul3U']

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
3981,3981,ybhS3G0ul3U,"Sir Ian Holm in ""Simon Magus"" (1999)","Sir Ian Holm as the Devil in ""Simon Magus"".",30.0,3.0,0.0,9.0,RIP . Why can i not find this movie anywhere ?...,600.0,8014.0

## Highest duration

In [72]:
df.sort_values(by='duration', ascending=False)[:1]

,index,youtubeId,title,description,likeCount,dislikeCount,favoriteCount,commentCount,comments_100,duration,viewCount
2077,2077,uwkfM-Gi7KU,Alfred Hitchcock: Blackmail and Easy Virtue,Two early films from the Master of Suspense po...,332.0,29.0,0.0,1.0,Wow this is just Great! Thanks for posting. Th...,9886.0,76301.0

In [18]:
df['duration']

0       PT1M31S
1       PT2M48S
2       PT1M51S
3       PT2M39S
5       PT2M28S
         ...
5298    PT2M11S
5300    PT1M15S
5301     PT2M4S
5302       PT2M
5303    PT4M50S
Name: duration, Length: 4182, dtype: object